### ISSUE TITLE
cannot convert some markdown into html

### ISSUE THREAD

**Issue by pwright** [ssorj/plano#3]
The following markdown causes a problem when converting to html

```bash
$ podman ps -a --format "{{.ID}}  {{.Image}}  {{.Labels}}
```

**Comment by ssorj** [comment]
Is the lack of a trailing quote intended there?

**Comment by pwright** [comment]
just a typo

**Comment by pwright** [comment]
I've got an ugly workaround at https://github.com/skupperproject/skupper-website/pull/80
which replaces `{{.ID}}` with `{{ID}}`  in the markdown, then defines `ID={{.ID}}` in config.py

**Comment by ssorj** [comment]
This is a Transom issue.  I addressed it by adding support for triple stash vars ({{{something}}}) as literal double stash vars ({{something}}).
